// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas de IU codificadas.
//      Versión: 14.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// fff
        /// </summary>
        public void OmplirAmbMerda()
        {
            #region Variable Declarations
            WpfButton uIOKButton = this.UIMainWindowWindow.UIOKButton;
            WpfEdit uITxtNomEdit = this.UIMainWindowWindow.UITxtNomEdit;
            #endregion

            // No se grabó la última acción de Row porque el control no tiene una propiedad de identificación correcta.

            // Clic 'Ok' botón
            Mouse.Click(uIOKButton, new Point(50, 13));

            // Escribir 'Raquelddddd' en cuadro de texto 'txtNom'
            uITxtNomEdit.Text = this.OmplirAmbMerdaParams.UITxtNomEditText;
        }
        
        /// <summary>
        /// ValidarMerda: use 'ValidarMerdaExpectedValues' para pasar parámetros a este método.
        /// </summary>
        public void ValidarMerda()
        {
            #region Variable Declarations
            WpfEdit uITxtNomEdit = this.UIMainWindowWindow.UITxtNomEdit;
            #endregion

            // Compruebe que la propiedad 'Text' de 'txtNom' cuadro de texto es igual a 'Raquelddddd'
            Assert.AreEqual(this.ValidarMerdaExpectedValues.UITxtNomEditText, uITxtNomEdit.Text);
        }
        
        #region Properties
        public virtual OmplirAmbMerdaParams OmplirAmbMerdaParams
        {
            get
            {
                if ((this.mOmplirAmbMerdaParams == null))
                {
                    this.mOmplirAmbMerdaParams = new OmplirAmbMerdaParams();
                }
                return this.mOmplirAmbMerdaParams;
            }
        }
        
        public virtual ValidarMerdaExpectedValues ValidarMerdaExpectedValues
        {
            get
            {
                if ((this.mValidarMerdaExpectedValues == null))
                {
                    this.mValidarMerdaExpectedValues = new ValidarMerdaExpectedValues();
                }
                return this.mValidarMerdaExpectedValues;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private OmplirAmbMerdaParams mOmplirAmbMerdaParams;
        
        private ValidarMerdaExpectedValues mValidarMerdaExpectedValues;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'OmplirAmbMerda'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class OmplirAmbMerdaParams
    {
        
        #region Fields
        /// <summary>
        /// Escribir 'Raquelddddd' en cuadro de texto 'txtNom'
        /// </summary>
        public string UITxtNomEditText = "Raquelddddd";
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'ValidarMerda'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class ValidarMerdaExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Compruebe que la propiedad 'Text' de 'txtNom' cuadro de texto es igual a 'Raquelddddd'
        /// </summary>
        public string UITxtNomEditText = "Raquelddddd";
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WpfButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnOk";
                    this.mUIOKButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        
        public WpfEdit UITxtNomEdit
        {
            get
            {
                if ((this.mUITxtNomEdit == null))
                {
                    this.mUITxtNomEdit = new WpfEdit(this);
                    #region Criterio de búsqueda
                    this.mUITxtNomEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtNom";
                    this.mUITxtNomEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtNomEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIOKButton;
        
        private WpfEdit mUITxtNomEdit;
        #endregion
    }
}
